#!/usr/bin/env python3
# Generated by braise's scaffold_brainlife_app.py, then hand-edited -- adapts
# segment_array.py (an existing CLI-style script, unmodified) to brainlife's
# config.json convention: load config.json, substitute its values into the
# --invoke command template from the app manifest, and run it.
#
# Hand-edits beyond the raw scaffold:
# - output_path is not a config.json key (outputs aren't part of brainlife's
#   config convention) -- it's fixed to output/data.ome.zarr, matching the
#   "output" id and neuro/ome-zarr's own file field (see manifest.json).
# - mask_path is an optional input; segment_array.py itself already turns the
#   literal string "None" back into Python None (see its own
#   `if value == "None": self.args[key] = None` conversion), so an absent/
#   empty config value is defaulted to "None" here rather than guessing at
#   how brainlife represents a skipped optional input.
import json
import shlex
import subprocess
import sys
import os

with open("config.json") as f:
    config = json.load(f)

config.setdefault("output_path", "output/data.ome.zarr")
config["mask_path"] = config.get("mask_path") or "None"
config["input_path"] = os.path.join(config["input_path"], "0")

command = (
    'bash -c "source activate ac && '
    "python3 /ac_segmentation/src/ac_segmentation/methods/segment_array.py "
    "--input_path {input_path} "
    "--weights_file /ac_segmentation/checkpoints/ac_set2_rg_1e-08_run7/best.ckpt "
    "--output_path {output_path} "
    "--mask_path {mask_path} "
    "--dsfactor {dsfactor} "
    "--rescale_perc '[96,97]'\""
).format(**config)
print(f"+ {command}")
result = subprocess.run(shlex.split(command))
sys.exit(result.returncode)
